### ISSUE TITLE
Console Window

### ISSUE THREAD

**Issue by m4444x** [schnotzler/winrun#1]
It works but it seems it opens a console window and quickly closes it again. Same as if I am running a batch file actually. So maybe I am doing something wrong? Can I avoid the window pop ( and loosing focus ) somehow?

**Comment by schnotzler** [comment]
You were using it right, the flashing console window is an annoyance. 
I will try to change to behaviour, however my first attempt #4fdb46e semms to not resolve the issue entirely, like i expected it to.

**Comment by schnotzler** [comment]
You were using it right, the flashing console window is an annoyance. 
I will try to change to behaviour, however my first attempt  seems to not resolve the issue entirely, like i expected it to.

**Comment by schnotzler** [comment]
Check out Release 0.2 updated the program with your suggestion. 
Watch out, because winrun.cfg syntax changed after this update.
I updated the `readme.md`to reflect the changes. Feel free to ask if you have any further questions or suggestions.

**Comment by schnotzler** [comment]
Depending on the Program you want to start `#NOFOCUS` may or may not work. I use it to launch Spotify for example, which sets its foccus regardless.

**Comment by schnotzler** [comment]
To avoid confusion:
And you were right about running a batchfile being the same as the old implementation btw.
In previous BandCamp releases they only allowed you to select .exe files for execution, which is why i wrote the program orginally.
It was basically a way to run (very simple) batch files through an .exe
